apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: dialog
  namespace: helsearbeidsgiver
spec:
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      memory: "1024Mi"
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-alive
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-ready
    periodSeconds: 10
    timeout: 1
  kafka:
    pool: nav-prod
  image: {{image}}
  accessPolicy:
    outbound:
      external:
       #  - host: platform.altinn.no
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
      rules:
        - application: logging
          namespace: nais-system
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: dialog
  envFrom:
    - secret: dialog-unleash-api-token
  env:
    - name: ALTINN_3_BASE_URL
      value: "https://platform.altinn.no"
    - name: ALTINN_DIALOGPORTEN_RESSURS
      value: "nav_sykepenger_dialog"
    - name: DIALOGPORTEN_SCOPE
      value: "digdir:dialogporten.serviceprovider"
    - name: NAV_ARBEIDSGIVER_API_BASEURL
      value: "https://sykepenger-api.nav.no"
    - name: NAV_ARBEIDSGIVER_GUI_BASEURL
      value: "https://arbeidsgiver.nav.no"
    - name: DOKUMENT_KOBLING_KAFKA_TOPIC
      value: helsearbeidsgiver.dokument-kobling
