apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: dialog
  namespace: helsearbeidsgiver
  annotations:
    texas.nais.io/enabled: "true"
spec:
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      memory: "1024Mi"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  image: {{image}}
  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
  azure:
    application:
      enabled: true
  envFrom:
    - secret: dialog-unleash-api-token
