apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: dialog
  namespace: helsearbeidsgiver
  annotations:
    texas.nais.io/enabled: "true"
spec:
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      memory: "1024Mi"
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-alive
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-ready
    periodSeconds: 10
    timeout: 1
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  image: {{image}}
  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
      rules:
        - application: logging
          namespace: nais-system
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
  azure:
    application:
      enabled: true
  envFrom:
    - secret: dialog-unleash-api-token
